export enum DocumentType {
	IDENTIFICATION = "IDENTIFICATION",
	PROOF_OF_INCOME = "PROOF_OF_INCOME",
	GUARANTOR_AGREEMENT = "GUARANTOR_AGREEMENT",
	LANDLORD_REFERENCE = "LANDLORD_REFERENCE",
	CHARACTER_REFERENCE = "CHARACTER_REFERENCE"
}
